# Site settings
title: Boyu Li
email: boyuli2001@foxmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal page of boyu
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://newsun-boki.github.io" # the base hostname & protocol for your site
# production_url: "https://www.domoritz.de"
github_username: newsun-boki
permalink: /blog/:year/:month/:title.html

twitter:
  username: liboyu

sass:
  style: compressed

collections:
  publications:
    output: false

jekyll-mentions:
  base_url: https://twitter.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
